version: '3.1'

services:
  db:
    image: postgres:13.1
    privileged: true
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: geekbrains
      POSTGRES_DB: db_todo

  backend:
    build:
      context: .
    expose:
      - 8080
    command: bash -c '
      ./wait-for-postgres.sh db &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py delete_all_users &&
      python manage.py create_superuser django &&
      python manage.py create_users 5 &&
      gunicorn todo_organizer.wsgi -b 0.0.0.0:8080
      '

    depends_on:
      - db

  nginx_backend:
    build: ./nginx_backend
    ports:
      - 8000:80
    depends_on:
      - backend

  nginx_frontend:
    build: ./nginx_frontend
    ports:
      - 80:80
    depends_on:
      - nginx_backend
